/**
 * auto-dashboard.ts — CloudWatch dashboard generator.
 *
 * Phase 5.6 of the migration: scans the stack for Lambdas, ECS services,
 * SQS queues, and SNS topics and emits a comprehensive dashboard. Saves
 * the human cost of maintaining a dashboard JSON by hand.
 *
 * Sections:
 *   1. Top-level — total invocations, errors, cost across all functions
 *   2. Per-Lambda — invocations, duration p99, errors, throttles
 *   3. ECS daemon — CPU, memory, task count, restarts
 *   4. SQS — depth, age of oldest, DLQ depth
 *   5. SNS — publish rate, delivery failures
 *   6. Aurora — connections, CPU, IO
 */

import * as cdk from 'aws-cdk-lib'
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch'
import * as ecs from 'aws-cdk-lib/aws-ecs'
import * as lambda from 'aws-cdk-lib/aws-lambda'
import * as sqs from 'aws-cdk-lib/aws-sqs'
import * as sns from 'aws-cdk-lib/aws-sns'
import { Construct } from 'constructs'

export interface AutoDashboardProps {
  readonly envName: string
  readonly lambdas: ReadonlyArray<{ label: string; fn: lambda.IFunction }>
  readonly ecsServices?: ReadonlyArray<{ label: string; service: ecs.IService; cluster: ecs.ICluster }>
  readonly sqsQueues?: ReadonlyArray<{ label: string; queue: sqs.IQueue; dlq?: sqs.IQueue }>
  readonly snsTopics?: ReadonlyArray<{ label: string; topic: sns.ITopic }>
  /** Aurora cluster identifier — referenced via DBClusterIdentifier dim. */
  readonly auroraClusterIdentifier?: string
}

export class AutoDashboardConstruct extends Construct {
  readonly dashboard: cloudwatch.Dashboard

  constructor(scope: Construct, id: string, props: AutoDashboardProps) {
    super(scope, id)

    this.dashboard = new cloudwatch.Dashboard(this, 'Dashboard', {
      dashboardName: `orbital-${props.envName}`,
      defaultInterval: cdk.Duration.hours(1),
    })

    // ----- 1. Top-level fleet view -----
    this.dashboard.addWidgets(
      new cloudwatch.TextWidget({
        markdown: `# Orbital — ${props.envName}\n\nAuto-generated by AutoDashboardConstruct. Edit the construct, not the dashboard JSON.`,
        width: 24,
        height: 2,
      }),
    )

    if (props.lambdas.length > 0) {
      const totalInvocations = new cloudwatch.MathExpression({
        expression: `SUM([${props.lambdas.map((_, i) => `m${i}`).join(',')}])`,
        usingMetrics: Object.fromEntries(
          props.lambdas.map((l, i) => [
            `m${i}`,
            l.fn.metric('Invocations', { statistic: 'Sum', period: cdk.Duration.minutes(1) }),
          ]),
        ),
        label: 'Total invocations',
      })
      const totalErrors = new cloudwatch.MathExpression({
        expression: `SUM([${props.lambdas.map((_, i) => `m${i}`).join(',')}])`,
        usingMetrics: Object.fromEntries(
          props.lambdas.map((l, i) => [
            `m${i}`,
            l.fn.metric('Errors', { statistic: 'Sum', period: cdk.Duration.minutes(1) }),
          ]),
        ),
        label: 'Total errors',
        color: '#D13212',
      })
      this.dashboard.addWidgets(
        new cloudwatch.GraphWidget({
          title: 'Lambda fleet — invocations',
          width: 12,
          left: [totalInvocations],
        }),
        new cloudwatch.GraphWidget({
          title: 'Lambda fleet — errors',
          width: 12,
          left: [totalErrors],
        }),
      )

      // ----- 2. Per-Lambda detail (4 widgets per row, batched) -----
      this.dashboard.addWidgets(
        new cloudwatch.TextWidget({
          markdown: '## Lambda functions',
          width: 24,
          height: 1,
        }),
      )
      const widgetsPerRow = 4
      for (let i = 0; i < props.lambdas.length; i += widgetsPerRow) {
        const row = props.lambdas.slice(i, i + widgetsPerRow)
        this.dashboard.addWidgets(
          ...row.map((l) =>
            new cloudwatch.GraphWidget({
              title: l.label,
              width: 24 / widgetsPerRow,
              left: [
                l.fn.metric('Invocations', { statistic: 'Sum' }),
                l.fn.metric('Errors', { statistic: 'Sum', color: '#D13212' }),
              ],
              right: [
                l.fn.metric('Duration', { statistic: 'p99', label: 'p99 ms' }),
              ],
            }),
          ),
        )
      }
    }

    // ----- 3. ECS services -----
    if (props.ecsServices && props.ecsServices.length > 0) {
      this.dashboard.addWidgets(
        new cloudwatch.TextWidget({ markdown: '## ECS services', width: 24, height: 1 }),
      )
      for (const svc of props.ecsServices) {
        this.dashboard.addWidgets(
          new cloudwatch.GraphWidget({
            title: `${svc.label} — CPU/Memory`,
            width: 12,
            left: [
              svc.service.metricCpuUtilization({ statistic: 'Average', label: 'CPU %' }),
              svc.service.metricMemoryUtilization({
                statistic: 'Average',
                label: 'Memory %',
                color: '#FF9900',
              }),
            ],
          }),
          new cloudwatch.GraphWidget({
            title: `${svc.label} — task counts`,
            width: 12,
            left: [
              new cloudwatch.Metric({
                namespace: 'AWS/ECS',
                metricName: 'CPUUtilization',
                statistic: 'SampleCount',
                dimensionsMap: {
                  ClusterName: svc.cluster.clusterName,
                  ServiceName: (svc.service as ecs.FargateService).serviceName ?? svc.label,
                },
                label: 'Reporting tasks',
              }),
            ],
          }),
        )
      }
    }

    // ----- 4. SQS depth + DLQ -----
    if (props.sqsQueues && props.sqsQueues.length > 0) {
      this.dashboard.addWidgets(
        new cloudwatch.TextWidget({ markdown: '## SQS queues', width: 24, height: 1 }),
      )
      for (const q of props.sqsQueues) {
        const depth = q.queue.metricApproximateNumberOfMessagesVisible({
          statistic: 'Maximum',
          label: 'Visible',
        })
        const oldest = q.queue.metricApproximateAgeOfOldestMessage({
          statistic: 'Maximum',
          label: 'Oldest age (s)',
        })
        const widgets: cloudwatch.IWidget[] = [
          new cloudwatch.GraphWidget({
            title: `${q.label} — depth + age`,
            width: 12,
            left: [depth],
            right: [oldest],
          }),
        ]
        if (q.dlq) {
          const dlqDepth = q.dlq.metricApproximateNumberOfMessagesVisible({
            statistic: 'Maximum',
            label: 'DLQ depth',
            color: '#D13212',
          })
          widgets.push(
            new cloudwatch.GraphWidget({
              title: `${q.label} — DLQ`,
              width: 12,
              left: [dlqDepth],
            }),
          )
        }
        this.dashboard.addWidgets(...widgets)
      }
    }

    // ----- 5. SNS publish + failures -----
    if (props.snsTopics && props.snsTopics.length > 0) {
      this.dashboard.addWidgets(
        new cloudwatch.TextWidget({ markdown: '## SNS topics', width: 24, height: 1 }),
      )
      for (const t of props.snsTopics) {
        this.dashboard.addWidgets(
          new cloudwatch.GraphWidget({
            title: `${t.label} — publishes`,
            width: 12,
            left: [
              t.topic.metricNumberOfMessagesPublished({ statistic: 'Sum' }),
            ],
          }),
          new cloudwatch.GraphWidget({
            title: `${t.label} — delivery failures`,
            width: 12,
            left: [
              t.topic.metricNumberOfNotificationsFailed({
                statistic: 'Sum',
                color: '#D13212',
              }),
            ],
          }),
        )
      }
    }

    // ----- 6. Aurora -----
    if (props.auroraClusterIdentifier !== undefined) {
      this.dashboard.addWidgets(
        new cloudwatch.TextWidget({ markdown: '## Aurora cluster', width: 24, height: 1 }),
        new cloudwatch.GraphWidget({
          title: 'Aurora — CPU + connections',
          width: 24,
          left: [
            new cloudwatch.Metric({
              namespace: 'AWS/RDS',
              metricName: 'CPUUtilization',
              statistic: 'Average',
              dimensionsMap: { DBClusterIdentifier: props.auroraClusterIdentifier },
              label: 'CPU %',
            }),
          ],
          right: [
            new cloudwatch.Metric({
              namespace: 'AWS/RDS',
              metricName: 'DatabaseConnections',
              statistic: 'Maximum',
              dimensionsMap: { DBClusterIdentifier: props.auroraClusterIdentifier },
              label: 'Connections',
            }),
          ],
        }),
      )
    }

    new cdk.CfnOutput(this, 'DashboardUrl', {
      value: `https://${cdk.Stack.of(this).region}.console.aws.amazon.com/cloudwatch/home?region=${cdk.Stack.of(this).region}#dashboards:name=orbital-${props.envName}`,
      description: `Orbital ${props.envName} CloudWatch dashboard URL`,
    })
  }
}
