/**
 * comms-workflow.ts — Drizzle schema for Phase 3A blocker / ceremony /
 * conflict-resolution / ADR tables.
 *
 * Per TRD-05 §4.3, §4.4, §4.5.
 *
 * Owned tables (this file):
 *   - blockers
 *   - ceremony_specifications
 *   - ceremonies
 *   - ceremony_participants
 *   - ceremony_outputs
 *   - disagreements
 *   - tie_breaker_decisions
 *   - adrs
 *
 * `adrs` carries an immutability trigger declared in 0007_comms.sql;
 * supersession is the only mutation allowed.
 */
export declare const BLOCKER_STATE: readonly ["raised", "routed", "in_resolution", "resolved", "escalated", "abandoned"];
export type BlockerState = (typeof BLOCKER_STATE)[number];
export declare const BLOCKER_URGENCY: readonly ["low", "normal", "high", "critical"];
export type BlockerUrgency = (typeof BLOCKER_URGENCY)[number];
export declare const CEREMONY_TYPE: readonly ["sprint_planning", "backlog_grooming", "architecture_review", "async_standup", "sprint_retrospective", "ad_hoc"];
export type CeremonyType = (typeof CEREMONY_TYPE)[number];
export declare const CEREMONY_STATE: readonly ["scheduled", "in_progress", "voting", "output_writing", "closed", "aborted"];
export type CeremonyState = (typeof CEREMONY_STATE)[number];
export declare const CEREMONY_VOTE_RULE: readonly ["simple_majority", "unanimous", "chair_decides"];
export type CeremonyVoteRule = (typeof CEREMONY_VOTE_RULE)[number];
export declare const CEREMONY_PARTICIPANT_ROLE: readonly ["chair", "participant", "observer"];
export type CeremonyParticipantRole = (typeof CEREMONY_PARTICIPANT_ROLE)[number];
export declare const CEREMONY_VOTE: readonly ["approve", "reject", "abstain", "approve_with_modifications"];
export type CeremonyVote = (typeof CEREMONY_VOTE)[number];
export declare const CEREMONY_OUTPUT_KIND: readonly ["sprint_commitment", "refined_backlog", "adr", "standup_digest", "retro_outcome", "partial"];
export type CeremonyOutputKind = (typeof CEREMONY_OUTPUT_KIND)[number];
export declare const DISAGREEMENT_STATE: readonly ["raised", "tie_breaker_assigned", "resolved", "escalated", "abandoned"];
export type DisagreementState = (typeof DISAGREEMENT_STATE)[number];
export declare const DISAGREEMENT_DOMAIN: readonly ["technical", "product", "security", "cross_cutting"];
export type DisagreementDomain = (typeof DISAGREEMENT_DOMAIN)[number];
export declare const ADR_STATUS: readonly ["proposed", "accepted", "superseded"];
export type AdrStatus = (typeof ADR_STATUS)[number];
export declare const blockers: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "blockers";
    schema: undefined;
    columns: {
        blockerId: import("drizzle-orm/pg-core").PgColumn<{
            name: "blocker_id";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        raisingActor: import("drizzle-orm/pg-core").PgColumn<{
            name: "raising_actor";
            tableName: "blockers";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        raisingTaskId: import("drizzle-orm/pg-core").PgColumn<{
            name: "raising_task_id";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ticketId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ticket_id";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        question: import("drizzle-orm/pg-core").PgColumn<{
            name: "question";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        context: import("drizzle-orm/pg-core").PgColumn<{
            name: "context";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        requestedResolverRole: import("drizzle-orm/pg-core").PgColumn<{
            name: "requested_resolver_role";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        urgency: import("drizzle-orm/pg-core").PgColumn<{
            name: "urgency";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgText";
            data: "critical" | "low" | "high" | "normal";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["low", "normal", "high", "critical"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        state: import("drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgText";
            data: "raised" | "routed" | "in_resolution" | "resolved" | "escalated" | "abandoned";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["raised", "routed", "in_resolution", "resolved", "escalated", "abandoned"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        routedToActor: import("drizzle-orm/pg-core").PgColumn<{
            name: "routed_to_actor";
            tableName: "blockers";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        routedToTaskId: import("drizzle-orm/pg-core").PgColumn<{
            name: "routed_to_task_id";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        routingAttempts: import("drizzle-orm/pg-core").PgColumn<{
            name: "routing_attempts";
            tableName: "blockers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        maxRoutingAttempts: import("drizzle-orm/pg-core").PgColumn<{
            name: "max_routing_attempts";
            tableName: "blockers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        originPostId: import("drizzle-orm/pg-core").PgColumn<{
            name: "origin_post_id";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        resolutionPostId: import("drizzle-orm/pg-core").PgColumn<{
            name: "resolution_post_id";
            tableName: "blockers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        raisedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "raised_at";
            tableName: "blockers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        resolvedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "resolved_at";
            tableName: "blockers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        escalatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "escalated_at";
            tableName: "blockers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "blockers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type BlockerRow = typeof blockers.$inferSelect;
export type BlockerInsert = typeof blockers.$inferInsert;
export declare const ceremonySpecifications: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ceremony_specifications";
    schema: undefined;
    columns: {
        specId: import("drizzle-orm/pg-core").PgColumn<{
            name: "spec_id";
            tableName: "ceremony_specifications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ceremonyType: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_type";
            tableName: "ceremony_specifications";
            dataType: "string";
            columnType: "PgText";
            data: "sprint_planning" | "backlog_grooming" | "architecture_review" | "async_standup" | "sprint_retrospective" | "ad_hoc";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["sprint_planning", "backlog_grooming", "architecture_review", "async_standup", "sprint_retrospective", "ad_hoc"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        version: import("drizzle-orm/pg-core").PgColumn<{
            name: "version";
            tableName: "ceremony_specifications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        chairRole: import("drizzle-orm/pg-core").PgColumn<{
            name: "chair_role";
            tableName: "ceremony_specifications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        participantRoles: import("drizzle-orm/pg-core").PgColumn<{
            name: "participant_roles";
            tableName: "ceremony_specifications";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        agendaTemplate: import("drizzle-orm/pg-core").PgColumn<{
            name: "agenda_template";
            tableName: "ceremony_specifications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        outputSchemaJson: import("drizzle-orm/pg-core").PgColumn<{
            name: "output_schema_json";
            tableName: "ceremony_specifications";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        defaultTurnsPerParticipant: import("drizzle-orm/pg-core").PgColumn<{
            name: "default_turns_per_participant";
            tableName: "ceremony_specifications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        defaultTokensPerTurn: import("drizzle-orm/pg-core").PgColumn<{
            name: "default_tokens_per_turn";
            tableName: "ceremony_specifications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        defaultWallClockMs: import("drizzle-orm/pg-core").PgColumn<{
            name: "default_wall_clock_ms";
            tableName: "ceremony_specifications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        voteRequired: import("drizzle-orm/pg-core").PgColumn<{
            name: "vote_required";
            tableName: "ceremony_specifications";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        voteRule: import("drizzle-orm/pg-core").PgColumn<{
            name: "vote_rule";
            tableName: "ceremony_specifications";
            dataType: "string";
            columnType: "PgText";
            data: "simple_majority" | "unanimous" | "chair_decides";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["simple_majority", "unanimous", "chair_decides"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "ceremony_specifications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        loadedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "loaded_at";
            tableName: "ceremony_specifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type CeremonySpecificationRow = typeof ceremonySpecifications.$inferSelect;
export type CeremonySpecificationInsert = typeof ceremonySpecifications.$inferInsert;
export declare const ceremonies: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ceremonies";
    schema: undefined;
    columns: {
        ceremonyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_id";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ceremonyType: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_type";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgText";
            data: "sprint_planning" | "backlog_grooming" | "architecture_review" | "async_standup" | "sprint_retrospective" | "ad_hoc";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["sprint_planning", "backlog_grooming", "architecture_review", "async_standup", "sprint_retrospective", "ad_hoc"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        specId: import("drizzle-orm/pg-core").PgColumn<{
            name: "spec_id";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        channelId: import("drizzle-orm/pg-core").PgColumn<{
            name: "channel_id";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        state: import("drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgText";
            data: "aborted" | "in_progress" | "scheduled" | "voting" | "output_writing" | "closed";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["scheduled", "in_progress", "voting", "output_writing", "closed", "aborted"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        triggeredBy: import("drizzle-orm/pg-core").PgColumn<{
            name: "triggered_by";
            tableName: "ceremonies";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        agendaPostId: import("drizzle-orm/pg-core").PgColumn<{
            name: "agenda_post_id";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        scope: import("drizzle-orm/pg-core").PgColumn<{
            name: "scope";
            tableName: "ceremonies";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        turnsPerParticipant: import("drizzle-orm/pg-core").PgColumn<{
            name: "turns_per_participant";
            tableName: "ceremonies";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tokensPerTurn: import("drizzle-orm/pg-core").PgColumn<{
            name: "tokens_per_turn";
            tableName: "ceremonies";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        wallClockBudgetMs: import("drizzle-orm/pg-core").PgColumn<{
            name: "wall_clock_budget_ms";
            tableName: "ceremonies";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tokensConsumedTotal: import("drizzle-orm/pg-core").PgColumn<{
            name: "tokens_consumed_total";
            tableName: "ceremonies";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        voteRule: import("drizzle-orm/pg-core").PgColumn<{
            name: "vote_rule";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgText";
            data: "simple_majority" | "unanimous" | "chair_decides";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["simple_majority", "unanimous", "chair_decides"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        voteRequired: import("drizzle-orm/pg-core").PgColumn<{
            name: "vote_required";
            tableName: "ceremonies";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        scheduledAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "scheduled_at";
            tableName: "ceremonies";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        startedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "started_at";
            tableName: "ceremonies";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        closedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "closed_at";
            tableName: "ceremonies";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        abortedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "aborted_at";
            tableName: "ceremonies";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        abortReason: import("drizzle-orm/pg-core").PgColumn<{
            name: "abort_reason";
            tableName: "ceremonies";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "ceremonies";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type CeremonyRow = typeof ceremonies.$inferSelect;
export type CeremonyInsert = typeof ceremonies.$inferInsert;
export declare const ceremonyParticipants: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ceremony_participants";
    schema: undefined;
    columns: {
        participantId: import("drizzle-orm/pg-core").PgColumn<{
            name: "participant_id";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ceremonyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_id";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        personaRole: import("drizzle-orm/pg-core").PgColumn<{
            name: "persona_role";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        personaId: import("drizzle-orm/pg-core").PgColumn<{
            name: "persona_id";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sessionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "session_id";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ceremonyRole: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_role";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgText";
            data: "chair" | "participant" | "observer";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["chair", "participant", "observer"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        turnsUsed: import("drizzle-orm/pg-core").PgColumn<{
            name: "turns_used";
            tableName: "ceremony_participants";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        turnsAllowed: import("drizzle-orm/pg-core").PgColumn<{
            name: "turns_allowed";
            tableName: "ceremony_participants";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        yieldedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "yielded_at";
            tableName: "ceremony_participants";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        voteCast: import("drizzle-orm/pg-core").PgColumn<{
            name: "vote_cast";
            tableName: "ceremony_participants";
            dataType: "string";
            columnType: "PgText";
            data: "approve" | "reject" | "abstain" | "approve_with_modifications";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["approve", "reject", "abstain", "approve_with_modifications"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        voteCastAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "vote_cast_at";
            tableName: "ceremony_participants";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type CeremonyParticipantRow = typeof ceremonyParticipants.$inferSelect;
export type CeremonyParticipantInsert = typeof ceremonyParticipants.$inferInsert;
export declare const ceremonyOutputs: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ceremony_outputs";
    schema: undefined;
    columns: {
        outputId: import("drizzle-orm/pg-core").PgColumn<{
            name: "output_id";
            tableName: "ceremony_outputs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ceremonyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_id";
            tableName: "ceremony_outputs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        outputKind: import("drizzle-orm/pg-core").PgColumn<{
            name: "output_kind";
            tableName: "ceremony_outputs";
            dataType: "string";
            columnType: "PgText";
            data: "partial" | "adr" | "sprint_commitment" | "standup_digest" | "retro_outcome" | "refined_backlog";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["sprint_commitment", "refined_backlog", "adr", "standup_digest", "retro_outcome", "partial"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        payload: import("drizzle-orm/pg-core").PgColumn<{
            name: "payload";
            tableName: "ceremony_outputs";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        authoredByActor: import("drizzle-orm/pg-core").PgColumn<{
            name: "authored_by_actor";
            tableName: "ceremony_outputs";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        capabilityId: import("drizzle-orm/pg-core").PgColumn<{
            name: "capability_id";
            tableName: "ceremony_outputs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        linkedAdrId: import("drizzle-orm/pg-core").PgColumn<{
            name: "linked_adr_id";
            tableName: "ceremony_outputs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isPartial: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_partial";
            tableName: "ceremony_outputs";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        unresolvedItems: import("drizzle-orm/pg-core").PgColumn<{
            name: "unresolved_items";
            tableName: "ceremony_outputs";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        writtenAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "written_at";
            tableName: "ceremony_outputs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "ceremony_outputs";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type CeremonyOutputRow = typeof ceremonyOutputs.$inferSelect;
export type CeremonyOutputInsert = typeof ceremonyOutputs.$inferInsert;
export declare const disagreements: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "disagreements";
    schema: undefined;
    columns: {
        disagreementId: import("drizzle-orm/pg-core").PgColumn<{
            name: "disagreement_id";
            tableName: "disagreements";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        domain: import("drizzle-orm/pg-core").PgColumn<{
            name: "domain";
            tableName: "disagreements";
            dataType: "string";
            columnType: "PgText";
            data: "technical" | "product" | "security" | "cross_cutting";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["technical", "product", "security", "cross_cutting"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        state: import("drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "disagreements";
            dataType: "string";
            columnType: "PgText";
            data: "raised" | "resolved" | "escalated" | "abandoned" | "tie_breaker_assigned";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["raised", "tie_breaker_assigned", "resolved", "escalated", "abandoned"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        detectionMode: import("drizzle-orm/pg-core").PgColumn<{
            name: "detection_mode";
            tableName: "disagreements";
            dataType: "string";
            columnType: "PgText";
            data: "explicit_flag" | "orchestrator_heuristic";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["explicit_flag", "orchestrator_heuristic"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        artifactRef: import("drizzle-orm/pg-core").PgColumn<{
            name: "artifact_ref";
            tableName: "disagreements";
            dataType: "json";
            columnType: "PgJsonb";
            data: {
                type: string;
                id: string;
            };
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        positions: import("drizzle-orm/pg-core").PgColumn<{
            name: "positions";
            tableName: "disagreements";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>[];
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        raisedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "raised_at";
            tableName: "disagreements";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tieBreakerAssignedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "tie_breaker_assigned_at";
            tableName: "disagreements";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        resolvedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "resolved_at";
            tableName: "disagreements";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        escalatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "escalated_at";
            tableName: "disagreements";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroFlagged: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_flagged";
            tableName: "disagreements";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "disagreements";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type DisagreementRow = typeof disagreements.$inferSelect;
export type DisagreementInsert = typeof disagreements.$inferInsert;
export declare const tieBreakerDecisions: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "tie_breaker_decisions";
    schema: undefined;
    columns: {
        decisionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "decision_id";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        disagreementId: import("drizzle-orm/pg-core").PgColumn<{
            name: "disagreement_id";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tieBreakerActor: import("drizzle-orm/pg-core").PgColumn<{
            name: "tie_breaker_actor";
            tableName: "tie_breaker_decisions";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tieBreakerRole: import("drizzle-orm/pg-core").PgColumn<{
            name: "tie_breaker_role";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decisionText: import("drizzle-orm/pg-core").PgColumn<{
            name: "decision_text";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rationale: import("drizzle-orm/pg-core").PgColumn<{
            name: "rationale";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        adrId: import("drizzle-orm/pg-core").PgColumn<{
            name: "adr_id";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        capabilityId: import("drizzle-orm/pg-core").PgColumn<{
            name: "capability_id";
            tableName: "tie_breaker_decisions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decidedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "decided_at";
            tableName: "tie_breaker_decisions";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "tie_breaker_decisions";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type TieBreakerDecisionRow = typeof tieBreakerDecisions.$inferSelect;
export type TieBreakerDecisionInsert = typeof tieBreakerDecisions.$inferInsert;
export declare const adrs: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "adrs";
    schema: undefined;
    columns: {
        adrId: import("drizzle-orm/pg-core").PgColumn<{
            name: "adr_id";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        adrNumber: import("drizzle-orm/pg-core").PgColumn<{
            name: "adr_number";
            tableName: "adrs";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        title: import("drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgText";
            data: "accepted" | "proposed" | "superseded";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["proposed", "accepted", "superseded"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        context: import("drizzle-orm/pg-core").PgColumn<{
            name: "context";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decision: import("drizzle-orm/pg-core").PgColumn<{
            name: "decision";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rationale: import("drizzle-orm/pg-core").PgColumn<{
            name: "rationale";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        consequences: import("drizzle-orm/pg-core").PgColumn<{
            name: "consequences";
            tableName: "adrs";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, string[]>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        alternatives: import("drizzle-orm/pg-core").PgColumn<{
            name: "alternatives";
            tableName: "adrs";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, string>[];
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        authoredByActor: import("drizzle-orm/pg-core").PgColumn<{
            name: "authored_by_actor";
            tableName: "adrs";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, unknown>;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        authoredByRole: import("drizzle-orm/pg-core").PgColumn<{
            name: "authored_by_role";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        capabilityId: import("drizzle-orm/pg-core").PgColumn<{
            name: "capability_id";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ceremonyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ceremony_id";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        disagreementId: import("drizzle-orm/pg-core").PgColumn<{
            name: "disagreement_id";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        supersedesAdrId: import("drizzle-orm/pg-core").PgColumn<{
            name: "supersedes_adr_id";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        supersededByAdrId: import("drizzle-orm/pg-core").PgColumn<{
            name: "superseded_by_adr_id";
            tableName: "adrs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        linkedTickets: import("drizzle-orm/pg-core").PgColumn<{
            name: "linked_tickets";
            tableName: "adrs";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        immutable: import("drizzle-orm/pg-core").PgColumn<{
            name: "immutable";
            tableName: "adrs";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "adrs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "adrs";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type AdrRow = typeof adrs.$inferSelect;
export type AdrInsert = typeof adrs.$inferInsert;
//# sourceMappingURL=comms-workflow.d.ts.map