/**
 * retros.ts - Drizzle schema for Phase 5B retro tables.
 *
 * Per TRD-10 v0.1 §4.
 *
 * Owned tables (this file):
 *   - retro_reports
 *   - retro_analyses
 *   - retro_proposals
 *   - retro_proposal_layers
 *   - system_versions
 *   - system_version_diffs
 *   - retro_outcomes
 *
 * Cross-context references (NOT redefined here):
 *   - sprints.sprint_id, sprint_commitments.sprint_id are owned by Phase 4B
 *     (db/schema/backlog.ts). retro_reports.sprint_id and proposal/outcome
 *     references to sprint_id are nullable uuids without physical FKs.
 *   - The additive sprint_commitments.system_version_id column is added by
 *     migration 0012_retros.sql but NOT redeclared in the Drizzle schema —
 *     Phase 4B owns the canonical typed column set; the migration is the
 *     additive evidence. RetroService reads this column via raw SQL only.
 *
 * Within-context FKs (real, enforced):
 *   - retro_analyses.retro_report_id -> retro_reports.retro_report_id
 *   - retro_proposals.retro_report_id -> retro_reports.retro_report_id
 *   - retro_proposal_layers.retro_proposal_id -> retro_proposals.retro_proposal_id (CASCADE)
 *   - system_version_diffs.system_version_id -> system_versions.system_version_id
 *   - system_version_diffs.retro_proposal_id -> retro_proposals.retro_proposal_id (nullable)
 *   - retro_outcomes.retro_proposal_id -> retro_proposals.retro_proposal_id
 *   - retro_outcomes.system_version_id -> system_versions.system_version_id
 */
export declare const RETRO_REPORT_STATUS: readonly ["analyzing", "ready", "reviewing", "closed", "failed"];
export type RetroReportStatus = (typeof RETRO_REPORT_STATUS)[number];
export declare const PROPOSAL_LAYER: readonly ["persona", "skill", "hook", "routing", "ceremony", "orchestrator", "environment", "board"];
export type ProposalLayer = (typeof PROPOSAL_LAYER)[number];
export declare const PROPOSAL_STATUS: readonly ["pending", "approved", "rejected", "deferred", "merged", "rolled_back"];
export type ProposalStatus = (typeof PROPOSAL_STATUS)[number];
export declare const PROPOSAL_CHANGE_TYPE: readonly ["create", "modify", "delete"];
export type ProposalChangeType = (typeof PROPOSAL_CHANGE_TYPE)[number];
export declare const VERSION_DIFF_CHANGE_TYPE: readonly ["added", "modified", "deleted"];
export type VersionDiffChangeType = (typeof VERSION_DIFF_CHANGE_TYPE)[number];
export declare const EXPECTED_DIRECTION: readonly ["increase", "decrease"];
export type ExpectedDirection = (typeof EXPECTED_DIRECTION)[number];
export declare const retroReports: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "retro_reports";
    schema: undefined;
    columns: {
        retroReportId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_report_id";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tenantId: import("drizzle-orm/pg-core").PgColumn<{
            name: "tenant_id";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sprintId: import("drizzle-orm/pg-core").PgColumn<{
            name: "sprint_id";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        systemVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "system_version_id";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        analysisRunSeq: import("drizzle-orm/pg-core").PgColumn<{
            name: "analysis_run_seq";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgText";
            data: "ready" | "closed" | "failed" | "analyzing" | "reviewing";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["analyzing", "ready", "reviewing", "closed", "failed"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        startedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "started_at";
            tableName: "retro_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        completedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "completed_at";
            tableName: "retro_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        proposalCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "proposal_count";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        approvedCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "approved_count";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rejectedCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "rejected_count";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        deferredCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "deferred_count";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroOnRetroAccuracy: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_on_retro_accuracy";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        failureReason: import("drizzle-orm/pg-core").PgColumn<{
            name: "failure_reason";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdEventId: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_event_id";
            tableName: "retro_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "retro_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type RetroReportRow = typeof retroReports.$inferSelect;
export type RetroReportInsert = typeof retroReports.$inferInsert;
export declare const retroAnalyses: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "retro_analyses";
    schema: undefined;
    columns: {
        retroAnalysisId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_analysis_id";
            tableName: "retro_analyses";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroReportId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_report_id";
            tableName: "retro_analyses";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        metricKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "metric_key";
            tableName: "retro_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        metricValue: import("drizzle-orm/pg-core").PgColumn<{
            name: "metric_value";
            tableName: "retro_analyses";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        prevSprintValue: import("drizzle-orm/pg-core").PgColumn<{
            name: "prev_sprint_value";
            tableName: "retro_analyses";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        pctDelta: import("drizzle-orm/pg-core").PgColumn<{
            name: "pct_delta";
            tableName: "retro_analyses";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        flagged: import("drizzle-orm/pg-core").PgColumn<{
            name: "flagged";
            tableName: "retro_analyses";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        computedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "computed_at";
            tableName: "retro_analyses";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        queryTraceRef: import("drizzle-orm/pg-core").PgColumn<{
            name: "query_trace_ref";
            tableName: "retro_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "retro_analyses";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type RetroAnalysisRow = typeof retroAnalyses.$inferSelect;
export type RetroAnalysisInsert = typeof retroAnalyses.$inferInsert;
export declare const retroProposals: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "retro_proposals";
    schema: undefined;
    columns: {
        retroProposalId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_proposal_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tenantId: import("drizzle-orm/pg-core").PgColumn<{
            name: "tenant_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroReportId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_report_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        proposalCode: import("drizzle-orm/pg-core").PgColumn<{
            name: "proposal_code";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        title: import("drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        hypothesis: import("drizzle-orm/pg-core").PgColumn<{
            name: "hypothesis";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expectedImpactMetric: import("drizzle-orm/pg-core").PgColumn<{
            name: "expected_impact_metric";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expectedImpactDirection: import("drizzle-orm/pg-core").PgColumn<{
            name: "expected_impact_direction";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: "increase" | "decrease";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["increase", "decrease"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expectedImpactPctPoints: import("drizzle-orm/pg-core").PgColumn<{
            name: "expected_impact_pct_points";
            tableName: "retro_proposals";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expectedImpactCi: import("drizzle-orm/pg-core").PgColumn<{
            name: "expected_impact_ci";
            tableName: "retro_proposals";
            dataType: "json";
            columnType: "PgJsonb";
            data: {
                low: number;
                high: number;
            } | null;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rollbackPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "rollback_path";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        evidenceRefs: import("drizzle-orm/pg-core").PgColumn<{
            name: "evidence_refs";
            tableName: "retro_proposals";
            dataType: "json";
            columnType: "PgJsonb";
            data: {
                event_id: string;
                aggregate_id?: string;
                summary: string;
            }[];
            driverParam: unknown;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appliesToSprintId: import("drizzle-orm/pg-core").PgColumn<{
            name: "applies_to_sprint_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isGlobal: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_global";
            tableName: "retro_proposals";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        currentValue: import("drizzle-orm/pg-core").PgColumn<{
            name: "current_value";
            tableName: "retro_proposals";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        proposedValue: import("drizzle-orm/pg-core").PgColumn<{
            name: "proposed_value";
            tableName: "retro_proposals";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        confidenceScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "confidence_score";
            tableName: "retro_proposals";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: "deferred" | "rejected" | "pending" | "merged" | "approved" | "rolled_back";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["pending", "approved", "rejected", "deferred", "merged", "rolled_back"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decidedBy: import("drizzle-orm/pg-core").PgColumn<{
            name: "decided_by";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decidedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "decided_at";
            tableName: "retro_proposals";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decisionRationale: import("drizzle-orm/pg-core").PgColumn<{
            name: "decision_rationale";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        prRef: import("drizzle-orm/pg-core").PgColumn<{
            name: "pr_ref";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mergedSystemVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "merged_system_version_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        deferredFromProposalId: import("drizzle-orm/pg-core").PgColumn<{
            name: "deferred_from_proposal_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdEventId: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_event_id";
            tableName: "retro_proposals";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "retro_proposals";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type RetroProposalRow = typeof retroProposals.$inferSelect;
export type RetroProposalInsert = typeof retroProposals.$inferInsert;
export declare const retroProposalLayers: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "retro_proposal_layers";
    schema: undefined;
    columns: {
        retroProposalLayerId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_proposal_layer_id";
            tableName: "retro_proposal_layers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroProposalId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_proposal_id";
            tableName: "retro_proposal_layers";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        layer: import("drizzle-orm/pg-core").PgColumn<{
            name: "layer";
            tableName: "retro_proposal_layers";
            dataType: "string";
            columnType: "PgText";
            data: "ceremony" | "persona" | "skill" | "hook" | "routing" | "orchestrator" | "environment" | "board";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["persona", "skill", "hook", "routing", "ceremony", "orchestrator", "environment", "board"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        targetPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "target_path";
            tableName: "retro_proposal_layers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        changeType: import("drizzle-orm/pg-core").PgColumn<{
            name: "change_type";
            tableName: "retro_proposal_layers";
            dataType: "string";
            columnType: "PgText";
            data: "create" | "modify" | "delete";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["create", "modify", "delete"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        diffPreview: import("drizzle-orm/pg-core").PgColumn<{
            name: "diff_preview";
            tableName: "retro_proposal_layers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isDominant: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_dominant";
            tableName: "retro_proposal_layers";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "retro_proposal_layers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type RetroProposalLayerRow = typeof retroProposalLayers.$inferSelect;
export type RetroProposalLayerInsert = typeof retroProposalLayers.$inferInsert;
export declare const systemVersions: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "system_versions";
    schema: undefined;
    columns: {
        systemVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "system_version_id";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        versionNumber: import("drizzle-orm/pg-core").PgColumn<{
            name: "version_number";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        parentSystemVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "parent_system_version_id";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitTag: import("drizzle-orm/pg-core").PgColumn<{
            name: "git_tag";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitSha: import("drizzle-orm/pg-core").PgColumn<{
            name: "git_sha";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        shippedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "shipped_at";
            tableName: "system_versions";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        shippedBy: import("drizzle-orm/pg-core").PgColumn<{
            name: "shipped_by";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isRollback: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_rollback";
            tableName: "system_versions";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rolledBackVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "rolled_back_version_id";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroReportId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_report_id";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        notes: import("drizzle-orm/pg-core").PgColumn<{
            name: "notes";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdEventId: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_event_id";
            tableName: "system_versions";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "system_versions";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type SystemVersionRow = typeof systemVersions.$inferSelect;
export type SystemVersionInsert = typeof systemVersions.$inferInsert;
export declare const systemVersionDiffs: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "system_version_diffs";
    schema: undefined;
    columns: {
        systemVersionDiffId: import("drizzle-orm/pg-core").PgColumn<{
            name: "system_version_diff_id";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        systemVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "system_version_id";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroProposalId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_proposal_id";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        layer: import("drizzle-orm/pg-core").PgColumn<{
            name: "layer";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        filePath: import("drizzle-orm/pg-core").PgColumn<{
            name: "file_path";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        changeType: import("drizzle-orm/pg-core").PgColumn<{
            name: "change_type";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgText";
            data: "added" | "modified" | "deleted";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["added", "modified", "deleted"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        unifiedDiff: import("drizzle-orm/pg-core").PgColumn<{
            name: "unified_diff";
            tableName: "system_version_diffs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "system_version_diffs";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type SystemVersionDiffRow = typeof systemVersionDiffs.$inferSelect;
export type SystemVersionDiffInsert = typeof systemVersionDiffs.$inferInsert;
export declare const retroOutcomes: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "retro_outcomes";
    schema: undefined;
    columns: {
        retroOutcomeId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_outcome_id";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retroProposalId: import("drizzle-orm/pg-core").PgColumn<{
            name: "retro_proposal_id";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        systemVersionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "system_version_id";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        metricKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "metric_key";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expectedDirection: import("drizzle-orm/pg-core").PgColumn<{
            name: "expected_direction";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgText";
            data: "increase" | "decrease";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["increase", "decrease"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expectedPctPoints: import("drizzle-orm/pg-core").PgColumn<{
            name: "expected_pct_points";
            tableName: "retro_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        windowSprintCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "window_sprint_count";
            tableName: "retro_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        windowStartSprintId: import("drizzle-orm/pg-core").PgColumn<{
            name: "window_start_sprint_id";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        windowEndSprintId: import("drizzle-orm/pg-core").PgColumn<{
            name: "window_end_sprint_id";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        baselineValue: import("drizzle-orm/pg-core").PgColumn<{
            name: "baseline_value";
            tableName: "retro_outcomes";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        actualPctPoints: import("drizzle-orm/pg-core").PgColumn<{
            name: "actual_pct_points";
            tableName: "retro_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        toleranceBand: import("drizzle-orm/pg-core").PgColumn<{
            name: "tolerance_band";
            tableName: "retro_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        matchedExpectation: import("drizzle-orm/pg-core").PgColumn<{
            name: "matched_expectation";
            tableName: "retro_outcomes";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        computedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "computed_at";
            tableName: "retro_outcomes";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        recordedEventId: import("drizzle-orm/pg-core").PgColumn<{
            name: "recorded_event_id";
            tableName: "retro_outcomes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        schemaVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "schema_version";
            tableName: "retro_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type RetroOutcomeRow = typeof retroOutcomes.$inferSelect;
export type RetroOutcomeInsert = typeof retroOutcomes.$inferInsert;
//# sourceMappingURL=retros.d.ts.map