import { z } from 'zod'

/**
 * Strongly-typed env config. Validated at startup; throws if required vars are missing.
 * Never read process.env outside of this module.
 */

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  LOG_LEVEL: z.enum(['trace', 'debug', 'info', 'warn', 'error', 'fatal', 'silent']).default('info'),

  DATABASE_URL: z
    .string()
    .url()
    .default('postgres://orbital:orbital_dev_password@localhost:5432/orbital'),

  PORT: z.coerce.number().int().positive().default(3000),
  HOST: z.string().default('0.0.0.0'),

  /** Anthropic API key — required at startup; workers call the real API. */
  ANTHROPIC_API_KEY: z.string().optional(),

  /**
   * Round 6 #8 — OpenAI API key.
   * When unset, the OpenAI driver loads but health() returns { healthy: false }.
   */
  OPENAI_API_KEY: z.string().optional(),

  /**
   * Round 6 #8 — AWS region for Bedrock driver.
   * Falls back to the standard AWS_REGION env var if unset.
   * When neither is set, the Bedrock driver health() returns { healthy: false }.
   */
  BEDROCK_AWS_REGION: z.string().optional(),

  /**
   * Round 6 #8 — provider fallback chain.
   * Comma-separated list of provider IDs in priority order.
   * Example: "anthropic,bedrock,openai"
   * Default: "anthropic"
   */
  MODEL_FALLBACK_CHAIN: z.string().default('anthropic'),

  /** Monday GraphQL token — required for backlog sync. */
  MONDAY_API_TOKEN: z.string().optional(),
  MONDAY_WEBHOOK_SECRET: z.string().optional(),

  /** GitHub token for API calls and PR management (Round 5D). Already exists as GITHUB_API_TOKEN. */
  GITHUB_API_TOKEN: z.string().optional(),
  /**
   * Round 5D — GitHub webhook secret.
   * HMAC-SHA256 shared secret configured in the GitHub repo/org webhook settings.
   * If absent at boot, the GitHub webhook route is not registered (same pattern
   * as MONDAY_WEBHOOK_SECRET).
   */
  GITHUB_WEBHOOK_SECRET: z.string().optional(),
  /**
   * Monday board id used by the periodic reconciler. When this is unset the
   * reconciler is registered as a no-op (warning logged at boot).
   */
  MONDAY_BOARD_ID: z.string().optional(),

  /** Path to the Claude Code CLI binary. */
  CLAUDE_BIN: z.string().default('claude'),

  /** Unix domain socket for the MCP gateway. */
  ORBITAL_MCP_GATEWAY_URL: z.string().default('unix:///tmp/orbital-mcp.sock'),

  /** Install root — defaults to ~/.orbital. */
  ORBITAL_HOME: z.string().optional(),

  /** OTel OTLP HTTP collector endpoint. */
  OTEL_EXPORTER_OTLP_ENDPOINT: z.string().optional(),

  /** Test-only file-based keychain shim flag. Never used in src/ for production logic. */
  ORBITAL_TEST_KEYCHAIN: z.coerce.boolean().default(false),

  /**
   * Round 7-03 — Override path for the install Ed25519 keypair file.
   * Defaults to `<ORBITAL_HOME or ~/.orbital>/keys/install.json`.
   * Tests use this to isolate parallel runs.
   * [Engineer-Principal · Opus · run-round7-03-federation-auth]
   */
  ORBITAL_INSTALL_KEY_PATH: z.string().optional(),

  /**
   * Round 7-03 — Hub master HMAC secret (HS256 over invite JWTs).
   * REQUIRED in hub mode. Generated by scripts/hub-bootstrap.sh.
   * Length must be >= 32 characters.
   * [Engineer-Principal · Opus · run-round7-03-federation-auth]
   */
  ORBITAL_HUB_MASTER_KEY: z.string().optional(),

  /**
   * Round 7-01 — Hub mode selector.
   *
   * 'local' (default) — boots everything as today: scheduler, spawn, worktrees,
   *   MCP gateway, Anthropic driver, cost ledger. 100% backwards compatible.
   *
   * 'hub' — boots Fastify + tRPC + WS + Postgres but skips:
   *   - scheduler.tick (no worker spawning)
   *   - spawn.ts (no claude binary lookup)
   *   - worktree.ts (no worktree management)
   *   - mcp/server.ts (no Unix socket)
   *   - Anthropic driver (no key needed)
   *   - Cost ledger writes (operators write to their own local ledger)
   *
   * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
   */
  ORBITAL_MODE: z.enum(['local', 'hub']).default('local'),

  /**
   * Round 7-01 — URL of the central hub this local Orbital connects to.
   * Only used when ORBITAL_MODE=local and the local client needs to reach the hub.
   * Example: 'https://orbital.team.dev'
   * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
   */
  ORBITAL_HUB_URL: z.string().url().optional(),

  /**
   * Round 7-01 — Tenant ID for this installation.
   * In 'hub' mode: the default tenant UUID when no X-Orbital-Tenant-ID header is present.
   * In 'local' mode: the single per-install tenant (defaults to the local-default sentinel).
   * Must be a valid UUID. When unset, defaults to the local-default sentinel UUID.
   * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
   */
  ORBITAL_HUB_TENANT_ID: z
    .string()
    .uuid()
    .default('00000000-0000-0000-0000-000000000000'),

  /**
   * Round 8-06 — Deployment target selector.
   * 'aws'   — use AWS services (S3Store for replay blobs, etc.)
   * 'local' — use local filesystem / self-hosted services (default)
   * [Engineer-Sr · Sonnet · run-round8-06-s3-cloudfront]
   */
  ORBITAL_DEPLOY_TARGET: z.enum(['aws', 'local']).default('local'),

  /**
   * Round 8-06 — S3 bucket name for replay blobs.
   * Required when ORBITAL_DEPLOY_TARGET=aws.
   * Set from CDK stack output OrbitalHub-<env>-ReplayBucketName.
   * Example: orbital-replays-mwitt-111111111111
   * [Engineer-Sr · Sonnet · run-round8-06-s3-cloudfront]
   */
  ORBITAL_REPLAY_BUCKET: z.string().optional(),

  /**
   * Round 8-06 — Default KMS key ARN for replay blob SSE-KMS encryption.
   * Required when ORBITAL_DEPLOY_TARGET=aws.
   * Set from CDK stack output OrbitalHub-<env>-ReplayKmsKeyArn.
   * Per-tenant CMKs added in 8-07.
   * [Engineer-Sr · Sonnet · run-round8-06-s3-cloudfront]
   */
  ORBITAL_REPLAY_KMS_KEY_ARN: z.string().optional(),

  /**
   * Round 8-05 — SNS topic ARN for event fanout.
   * Required when ORBITAL_DEPLOY_TARGET=aws.
   * Set from CDK stack output OrbitalHub-<env>-EventsTopicArn.
   * Example: arn:aws:sns:us-east-1:111111111111:orbital-events-mwitt
   * [Engineer-Sr · Sonnet · run-round8-05-event-bus]
   */
  EVENTS_TOPIC_ARN: z.string().optional(),

  /**
   * Round 6 #1 — GitHub PR loop feature flag.
   * When 'on', post-task hook pushes branch and opens PR after verifier passes.
   * Default 'off' — safe to ship without a GitHub remote configured.
   * [Engineer-Sr · Sonnet · run-round6-01-pr-loop]
   */
  ORBITAL_PR_LOOP: z.enum(['on', 'off']).default('off'),

  // ------------------------------------------------------------------
  // Round 8-02 — Aurora/RDS Proxy connection config
  // ORBITAL_DEPLOY_TARGET is defined above (Round 8-06 owns the field;
  // 8-02 extends its semantics for the DB client IAM auth branch).
  // When ORBITAL_DEPLOY_TARGET=aws the DB client uses IAM auth via RDS Proxy.
  // [Engineer-Sr · Sonnet · run-round8-02-aurora]
  // ------------------------------------------------------------------

  /**
   * Round 8-02 — RDS Proxy hostname.
   * Set by Lambda environment config (8-03). Required when ORBITAL_DEPLOY_TARGET=aws.
   * Example: orbital-mwitt-proxy.proxy-xxxx.us-east-1.rds.amazonaws.com
   * [Engineer-Sr · Sonnet · run-round8-02-aurora]
   */
  RDS_PROXY_HOSTNAME: z.string().optional(),

  /**
   * Round 8-02 — RDS Proxy port. Defaults to 5432.
   * [Engineer-Sr · Sonnet · run-round8-02-aurora]
   */
  RDS_PROXY_PORT: z.coerce.number().int().positive().default(5432),

  /**
   * Round 8-02 — Aurora database name. Defaults to 'orbital_hub'.
   * [Engineer-Sr · Sonnet · run-round8-02-aurora]
   */
  AURORA_DB_NAME: z.string().default('orbital_hub'),

  /**
   * Round 8-02 — Aurora/RDS Proxy IAM username.
   * The user must exist in Aurora and have been granted rds_iam in Aurora,
   * or have the rds-db:connect IAM permission. Defaults to 'orbital_admin'.
   * [Engineer-Sr · Sonnet · run-round8-02-aurora]
   */
  AURORA_USERNAME: z.string().default('orbital_admin'),

  /**
   * Round 3 S1 — CORS allowlist.
   * Comma-separated list of origins allowed to make cross-origin requests.
   * - In `production`: empty default; if empty at boot we log a loud warning
   *   ("CORS will reject all browser traffic; set CORS_ALLOWED_ORIGINS=...").
   * - In `development`: ignored — origin: true is used so any local dev server
   *   (Vite, Storybook, etc.) can call the API.
   * - In `test`: empty default; tests that exercise CORS set it explicitly.
   *
   * Use the literal `*` to allow all origins (dangerous; only meaningful in
   * test/dev). The validator rejects `*` in production.
   */
  CORS_ALLOWED_ORIGINS: z.string().default(''),

  /**
   * Round 3 S4 — WebSocket session token.
   * If set, every WS upgrade request must present this token via the
   * `x-orbital-ws-token` header OR the `?token=...` query parameter.
   *
   * In dev (NODE_ENV=development) with this var unset, WS connections are
   * accepted unauthenticated and a loud warning is emitted at boot. In
   * production it is strongly recommended to set this; an unset token means
   * any reachable client can subscribe to live event streams.
   */
  WS_SESSION_TOKEN: z.string().optional(),
})

export type Env = z.infer<typeof envSchema>

let cached: Env | null = null

export function loadEnv(): Env {
  if (cached) return cached
  const parsed = envSchema.safeParse(process.env)
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((i) => `  - ${i.path.join('.')}: ${i.message}`)
      .join('\n')
    throw new Error(`Invalid environment configuration:\n${issues}`)
  }
  cached = parsed.data
  return cached
}

/** Reset for tests. */
export function resetEnvCache(): void {
  cached = null
}

/** Convenience accessor — typed env. */
export const env = new Proxy({} as Env, {
  get(_t, prop: string) {
    const e = loadEnv()
    return e[prop as keyof Env]
  },
})

/** Resolve install root with default. */
export function getOrbitalHome(): string {
  const e = loadEnv()
  if (e.ORBITAL_HOME) return e.ORBITAL_HOME
  const home = process.env.HOME ?? process.env.USERPROFILE
  if (!home) throw new Error('Cannot resolve user home directory')
  return `${home}/.orbital`
}

/** Hard-required getter — throws if missing. */
export function requireEnv<K extends keyof Env>(key: K): NonNullable<Env[K]> {
  const value = loadEnv()[key]
  if (value === undefined || value === null || value === '') {
    throw new Error(
      `STARTUP_ERROR: required env var ${String(key)} is not set. ` +
        `See .env.example for documentation.`,
    )
  }
  return value as NonNullable<Env[K]>
}
