/**
 * backlog.ts — Drizzle schema for Phase 4B backlog + sprint + Monday-sync tables.
 *
 * Per TRD-02 v0.2 §4.
 *
 * Owned tables (this file):
 *   - epics
 *   - stories
 *   - story_acceptance_criteria
 *   - sprints
 *   - sprint_commitments
 *   - monday_sync_state
 *
 * Cross-context references (NOT redefined here):
 *   - tasks, task_dependencies → owned by TRD-04 (db/schema/orchestration.ts)
 *   - defects → owned by TRD-11 (future migration)
 *   - vision_versions → owned by TRD-01 (Phase 4A migration 0009)
 *
 * Within-context FKs (allowed): stories.epic_id → epics.epic_id;
 * story_acceptance_criteria.story_id → stories.story_id ON DELETE CASCADE.
 * Cross-context references are nullable uuid columns without physical FKs
 * (consistent with TRD-04 §4.1 reconciliation note pattern).
 *
 * Migration 0018 (auto_generated_metadata):
 *   - epics.auto_generated_metadata  (nullable jsonb)
 *   - stories.auto_generated_metadata (nullable jsonb)
 *   Set by VisionAutoDecomposeSubscriber when auto-generating starter backlog
 *   from a locked vision. Shape: { source, vision_document_id, version }.
 */

import {
  pgTable,
  uuid,
  text,
  integer,
  jsonb,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

// ---------------------------------------------------------------------------
// Enum constants
// ---------------------------------------------------------------------------

export const EPIC_STATUS = [
  'draft',
  'active',
  'completed',
  'archived',
  // Added by migration 0019: hygiene sweep transitions test/fixture epics to
  // this status without deleting them, preserving the audit trail.
  'cancelled',
] as const
export type EpicStatus = (typeof EPIC_STATUS)[number]

export const STORY_STATUS = [
  'backlog',
  'ready',
  'in_progress',
  'in_review',
  'done',
  'accepted',
  'blocked',
  'defective',
  // Added by migration 0016: hygiene sweep transitions fixture stories to
  // this status without deleting them, preserving the audit trail.
  'cancelled',
] as const
export type StoryStatus = (typeof STORY_STATUS)[number]

export const SPRINT_STATUS = [
  'planning',
  'ready',
  'active',
  'completing',
  'completed',
  'paused',
] as const
export type SprintStatus = (typeof SPRINT_STATUS)[number]

export const SPRINT_PRIORITY_CLASS = ['critical', 'standard', 'background'] as const
export type SprintPriorityClass = (typeof SPRINT_PRIORITY_CLASS)[number]

export const MONDAY_AGGREGATE_TYPE = [
  'epic',
  'story',
  'task',
  'sprint',
  'defect',
] as const
export type MondayAggregateType = (typeof MONDAY_AGGREGATE_TYPE)[number]

// ---------------------------------------------------------------------------
// epics
// ---------------------------------------------------------------------------

/**
 * Per TRD-02 v0.2 §4.1.
 *
 * One epic groups N stories. Linked to a vision version. Priority is dense.
 */
export const epics = pgTable(
  'epics',
  {
    epicId: uuid('epic_id').primaryKey(),
    /**
     * Round 7-01 — Multi-tenant scoping.
     * Sentinel '00000000-0000-0000-0000-000000000000' = local-install default.
     * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
     */
    tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
    /**
     * fix/multi-project-isolation — multi-project scoping.
     * Mirrors migration 0015. Nullable until backfill (0045) + NOT NULL (0046).
     * [Engineer-Principal · Opus · run-multi-project-isolation]
     */
    projectId: uuid('project_id'),
    visionVersionId: uuid('vision_version_id').notNull(),
    title: text('title').notNull(),
    rationale: text('rationale').notNull(),
    priority: integer('priority').notNull(),
    mondayGroupId: text('monday_group_id'),
    status: text('status', { enum: EPIC_STATUS }).notNull().default('draft'),
    /**
     * Migration 0018: set by VisionAutoDecomposeSubscriber when auto-generating
     * starter epics from a locked vision. NULL for manually-created epics.
     * Shape: { source: 'vision_lock', vision_document_id: string, version: number }
     */
    autoGeneratedMetadata: jsonb('auto_generated_metadata')
      .$type<{
        source: 'vision_lock'
        vision_document_id: string
        version: number
      } | null>()
      .default(null),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    schemaVersion: integer('schema_version').notNull().default(1),
  },
  (t) => ({
    byVision: index('epics_vision_idx').on(t.visionVersionId),
    byPriority: index('epics_priority_idx').on(t.priority),
    byProject: index('epics_project_idx').on(t.projectId),
  }),
)

export type EpicRow = typeof epics.$inferSelect
export type EpicInsert = typeof epics.$inferInsert

// ---------------------------------------------------------------------------
// stories
// ---------------------------------------------------------------------------

/**
 * Per TRD-02 v0.2 §4.1.
 */
export const stories = pgTable(
  'stories',
  {
    storyId: uuid('story_id').primaryKey(),
    /**
     * Round 7-01 — Multi-tenant scoping.
     * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
     */
    tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
    /** fix/multi-project-isolation — see epics.projectId. */
    projectId: uuid('project_id'),
    epicId: uuid('epic_id').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    status: text('status', { enum: STORY_STATUS }).notNull().default('backlog'),
    storyPoints: integer('story_points'),
    priority: integer('priority').notNull(),
    personaOfRecord: text('persona_of_record'),
    mondayItemId: text('monday_item_id'),
    originStoryId: uuid('origin_story_id'),
    defectId: uuid('defect_id'),
    linkedArtifacts: jsonb('linked_artifacts')
      .$type<Array<{ type: string; id: string; url?: string }>>()
      .notNull()
      .default([]),
    /**
     * Migration 0018: set by VisionAutoDecomposeSubscriber when auto-generating
     * starter stories from a locked vision. NULL for manually-created stories.
     * Shape: { source: 'vision_lock', vision_document_id: string, version: number }
     */
    autoGeneratedMetadata: jsonb('auto_generated_metadata')
      .$type<{
        source: 'vision_lock'
        vision_document_id: string
        version: number
      } | null>()
      .default(null),
    /**
     * Migration 0040: reviewer feedback when a story is sent back from review.
     * Set by stories.redirect, cleared when StoryExecutor next picks the story up.
     * NULL means no pending redirect.
     * [Engineer-Principal · Opus · run-orbital-review-ui]
     */
    redirectNote: text('redirect_note'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    schemaVersion: integer('schema_version').notNull().default(1),
  },
  (t) => ({
    byEpic: index('stories_epic_idx').on(t.epicId),
    byStatus: index('stories_status_idx').on(t.status),
    byOrigin: index('stories_origin_idx').on(t.originStoryId),
    byProject: index('stories_project_idx').on(t.projectId),
  }),
)

export type StoryRow = typeof stories.$inferSelect
export type StoryInsert = typeof stories.$inferInsert

// ---------------------------------------------------------------------------
// story_acceptance_criteria
// ---------------------------------------------------------------------------

/**
 * Per TRD-02 v0.2 §4.1. ACs are first-class so UAT (TRD-11) can reference
 * individual ACs by ID. ON DELETE CASCADE is appropriate within the backlog
 * context.
 */
export const storyAcceptanceCriteria = pgTable(
  'story_acceptance_criteria',
  {
    acId: uuid('ac_id').primaryKey(),
    /**
     * Round 7-01 — Multi-tenant scoping.
     * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
     */
    tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
    storyId: uuid('story_id').notNull(),
    ordinal: integer('ordinal').notNull(),
    text: text('text').notNull(),
    verifierHint: text('verifier_hint'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    schemaVersion: integer('schema_version').notNull().default(1),
  },
  (t) => ({
    byStory: index('ac_story_idx').on(t.storyId),
    uniqueOrdinal: uniqueIndex('ac_unique_ordinal_idx').on(t.storyId, t.ordinal),
  }),
)

export type StoryAcceptanceCriterionRow = typeof storyAcceptanceCriteria.$inferSelect
export type StoryAcceptanceCriterionInsert = typeof storyAcceptanceCriteria.$inferInsert

// ---------------------------------------------------------------------------
// sprints
// ---------------------------------------------------------------------------

/**
 * Per TRD-02 v0.2 §4.3.
 *
 * Multi-sprint coordination via concurrencyShare + priorityClass.
 */
export const sprints = pgTable(
  'sprints',
  {
    sprintId: uuid('sprint_id').primaryKey(),
    /**
     * Round 7-01 — Multi-tenant scoping.
     * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
     */
    tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
    /** fix/multi-project-isolation — see epics.projectId. */
    projectId: uuid('project_id'),
    name: text('name').notNull(),
    sequence: integer('sequence').notNull(),
    status: text('status', { enum: SPRINT_STATUS }).notNull().default('planning'),
    storyPointCapacity: integer('story_point_capacity').notNull(),
    wallClockTargetMs: integer('wall_clock_target_ms'),
    budgetUsdCents: integer('budget_usd_cents').notNull(),
    concurrencyShare: integer('concurrency_share').notNull().default(100),
    priorityClass: text('priority_class', { enum: SPRINT_PRIORITY_CLASS })
      .notNull()
      .default('standard'),
    sprintChannelId: uuid('sprint_channel_id'),
    mondayBoardGroupId: text('monday_board_group_id'),
    startedAt: timestamp('started_at', { withTimezone: true, mode: 'date' }),
    pausedAt: timestamp('paused_at', { withTimezone: true, mode: 'date' }),
    completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }),
    pauseState: jsonb('pause_state').$type<SprintPauseState | null>(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    schemaVersion: integer('schema_version').notNull().default(1),
  },
  (t) => ({
    byStatus: index('sprints_status_idx').on(t.status),
    bySequence: index('sprints_sequence_idx').on(t.sequence),
    byProject: index('sprints_project_idx').on(t.projectId),
  }),
)

export type SprintRow = typeof sprints.$inferSelect
export type SprintInsert = typeof sprints.$inferInsert

export interface SprintPauseState {
  in_flight_task_ids: string[]
  worker_session_ids: string[]
  capability_ids_to_revoke: string[]
  dag_cursor: { ready: string[]; pending: string[] }
  paused_at: string
}

// ---------------------------------------------------------------------------
// sprint_commitments
// ---------------------------------------------------------------------------

/**
 * Per TRD-02 v0.2 §4.3.
 *
 * One commitment row per sprint, written by the planning ceremony's chair (or
 * synthetically by the SprintService for non-ceremony-driven sprints).
 */
export const sprintCommitments = pgTable(
  'sprint_commitments',
  {
    commitmentId: uuid('commitment_id').primaryKey(),
    /**
     * Round 7-01 — Multi-tenant scoping.
     * [Engineer-Sr · Sonnet · run-round7-01-extract-hub]
     */
    tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
    sprintId: uuid('sprint_id').notNull(),
    ceremonyId: uuid('ceremony_id'),
    selectedStoryIds: jsonb('selected_story_ids').$type<string[]>().notNull(),
    capacityUsedPoints: integer('capacity_used_points').notNull(),
    identifiedRisks: jsonb('identified_risks')
      .$type<
        Array<{
          risk: string
          severity: 'low' | 'medium' | 'high'
          mitigation: string | null
        }>
      >()
      .notNull()
      .default([]),
    raisedConcerns: jsonb('raised_concerns')
      .$type<
        Array<{
          raisedBy: string
          concern: string
          disposition: 'accepted' | 'deferred' | 'rejected'
          rationale: string
        }>
      >()
      .notNull()
      .default([]),
    isPartial: boolean('is_partial').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    schemaVersion: integer('schema_version').notNull().default(1),
  },
  (t) => ({
    bySprint: uniqueIndex('sprint_commitments_sprint_uq').on(t.sprintId),
  }),
)

export type SprintCommitmentRow = typeof sprintCommitments.$inferSelect
export type SprintCommitmentInsert = typeof sprintCommitments.$inferInsert

// ---------------------------------------------------------------------------
// monday_sync_state
// ---------------------------------------------------------------------------

/**
 * Per TRD-02 v0.2 §4.4.
 *
 * Bidirectional drift-aware sync mapping for a single Orbital aggregate to
 * Monday.com. last_seen_item_ids is added in this phase to track items the
 * reconciliation pull last observed (TRD-02 §13.3).
 */
export const mondaySyncState = pgTable(
  'monday_sync_state',
  {
    syncStateId: uuid('sync_state_id').primaryKey(),
    aggregateType: text('aggregate_type', { enum: MONDAY_AGGREGATE_TYPE }).notNull(),
    aggregateId: uuid('aggregate_id').notNull(),
    mondayId: text('monday_id').notNull(),
    lastPushAt: timestamp('last_push_at', { withTimezone: true, mode: 'date' }),
    lastPullAt: timestamp('last_pull_at', { withTimezone: true, mode: 'date' }),
    lastPushHash: text('last_push_hash'),
    lastPullHash: text('last_pull_hash'),
    lastSeenItemIds: jsonb('last_seen_item_ids').$type<string[]>().notNull().default([]),
    driftDetectedAt: timestamp('drift_detected_at', { withTimezone: true, mode: 'date' }),
    syncErrorCount: integer('sync_error_count').notNull().default(0),
    lastError: text('last_error'),
    schemaVersion: integer('schema_version').notNull().default(1),
  },
  (t) => ({
    byAggregate: uniqueIndex('monday_sync_aggregate_uq').on(t.aggregateType, t.aggregateId),
    byMondayId: index('monday_sync_monday_idx').on(t.mondayId),
  }),
)

export type MondaySyncStateRow = typeof mondaySyncState.$inferSelect
export type MondaySyncStateInsert = typeof mondaySyncState.$inferInsert
