/**
 * onboarding/system-teacher.ts — generates per-project SDLC context that
 * persona briefs and skills load when working on a project.
 *
 * Round 9 — Onboarding UX Overhaul
 * [Engineer-Principal · Opus · run-round9-onboarding-overhaul]
 *
 * Outputs:
 *   1. Project CLAUDE.md — committed to the repo via the GitHub provisioner.
 *   2. Skill bundle config — `~/.orbital/projects/<project-id>/skills.json`.
 *   3. Optionally: project_memory_entries seeded by memory-seeder.ts.
 *
 * Emits ProjectSDLCConfigured on completion.
 */

import path from 'node:path'
import { promises as fs } from 'node:fs'
import { uuidv7 } from 'uuidv7'
import type { Actor } from '@orbital/types'
import type { EventStore } from '../events/store.js'
import { getOrbitalHome } from '../config/env.js'
import type { ProjectSDLCConfiguredPayload } from '../events/types.js'
import type { DefaultGithubProvisioner } from './github-provisioner.js'
import { logger } from '../config/logger.js'

const SYSTEM_ACTOR: Actor = { type: 'system', component: 'orchestrator' }

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface TeachSystemInput {
  sessionId: string
  projectId: string
  projectName: string
  /** GitHub coordinates (only when committing CLAUDE.md to a real repo). */
  github?: {
    owner: string
    repo: string
  }
  /** Vision excerpt + chosen stack — drives the CLAUDE.md template. */
  vision?: { intent: string; stack: string[] }
  /** Output of analysis (for Flow B). */
  analysis?: {
    stack: string[]
    testRunner: string | null
    commitConvention: string | null
    branchModel: string | null
  }
  /** Monday board id, if provisioned. */
  mondayBoardId?: string | null
  /** Memory entry IDs already seeded for this project. */
  memoryEntryIds: string[]
  /** Skills to enable (defaults applied if empty). */
  skills?: string[]
}

export interface TeachSystemResult {
  claudeMdCommitted: boolean
  claudeMdSha: string | null
  skillsEnabled: string[]
  /** Path to the per-project skills config that was written locally. */
  skillsConfigPath: string
}

export interface SystemTeacher {
  teach(input: TeachSystemInput): Promise<TeachSystemResult>
}

// ---------------------------------------------------------------------------
// CLAUDE.md template
// ---------------------------------------------------------------------------

function generateClaudeMd(input: TeachSystemInput): string {
  const stack = input.vision?.stack ?? input.analysis?.stack ?? []
  const lines: string[] = []
  lines.push(`# CLAUDE.md`)
  lines.push('')
  lines.push(`> Project-level instructions for Claude on **${input.projectName}**.`)
  lines.push(`> Generated by Orbital onboarding on ${new Date().toISOString().slice(0, 10)}.`)
  lines.push('')
  if (input.vision?.intent) {
    lines.push(`## Project intent`)
    lines.push('')
    lines.push(input.vision.intent.trim())
    lines.push('')
  }
  if (stack.length > 0) {
    lines.push(`## Stack`)
    lines.push('')
    for (const s of stack) lines.push(`- ${s}`)
    lines.push('')
  }
  lines.push(`## SDLC`)
  lines.push('')
  lines.push(`- Tickets live in Monday${input.mondayBoardId ? ` (board ${input.mondayBoardId})` : ''}.`)
  if (input.github) {
    lines.push(`- PRs live in \`${input.github.owner}/${input.github.repo}\`.`)
  }
  if (input.analysis?.commitConvention) {
    lines.push(`- Commit messages follow ${input.analysis.commitConvention}.`)
  }
  if (input.analysis?.branchModel) {
    lines.push(`- Branch model: ${input.analysis.branchModel}.`)
  }
  if (input.analysis?.testRunner) {
    lines.push(`- Tests run with ${input.analysis.testRunner}.`)
  }
  lines.push('')
  lines.push(`## Memory`)
  lines.push('')
  lines.push(
    `${input.memoryEntryIds.length} memory entries are seeded for this project. Persona briefs auto-load relevant entries when the agent is briefed.`,
  )
  lines.push('')
  lines.push(`## Real implementations only`)
  lines.push('')
  lines.push(
    `No mocks in \`src/\`. No placeholder data. If a feature can't be implemented end-to-end, the agent must say so explicitly rather than ship a fake.`,
  )
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Skill defaults
// ---------------------------------------------------------------------------

const FRONTEND_SKILLS = ['design-fidelity', 'tailwind-conventions', 'a11y-baseline']
const BACKEND_SKILLS = ['multi-tenant-isolation', 'api-design', 'security-defaults']
const DEFAULT_SKILLS = [
  'sdlc-monday-board',
  'tdd-workflow',
  'branch-pr-strategy',
  ...BACKEND_SKILLS,
]

function defaultSkillsForStack(stack: string[]): string[] {
  const set = new Set<string>(DEFAULT_SKILLS)
  if (stack.includes('react') || stack.includes('vue') || stack.includes('nextjs') || stack.includes('tailwind')) {
    for (const s of FRONTEND_SKILLS) set.add(s)
  }
  return Array.from(set)
}

// ---------------------------------------------------------------------------
// Implementation
// ---------------------------------------------------------------------------

export class DefaultSystemTeacher implements SystemTeacher {
  constructor(
    private readonly eventStore: EventStore,
    private readonly githubProvisioner: DefaultGithubProvisioner | null,
  ) {}

  async teach(input: TeachSystemInput): Promise<TeachSystemResult> {
    const stack = input.vision?.stack ?? input.analysis?.stack ?? []
    const enabled = input.skills && input.skills.length > 0 ? input.skills : defaultSkillsForStack(stack)

    const claudeMd = generateClaudeMd(input)

    // 1. Commit CLAUDE.md to the repo (when GitHub is connected).
    let committed = false
    let claudeMdSha: string | null = null
    if (input.github && this.githubProvisioner) {
      try {
        claudeMdSha = await this.githubProvisioner.commitFile(
          input.github.owner,
          input.github.repo,
          'CLAUDE.md',
          claudeMd,
          'docs: add project CLAUDE.md (Orbital onboarding)',
        )
        committed = claudeMdSha !== null
      } catch (err) {
        logger.warn(
          { err: err instanceof Error ? err.message : String(err) },
          'system-teacher: CLAUDE.md commit failed',
        )
      }
    }

    // 2. Write per-project skills.json under ORBITAL_HOME.
    const projectDir = path.join(getOrbitalHome(), 'projects', input.projectId)
    await fs.mkdir(projectDir, { recursive: true, mode: 0o700 })
    const skillsPath = path.join(projectDir, 'skills.json')
    const skillsContent = JSON.stringify(
      {
        version: 1,
        projectId: input.projectId,
        projectName: input.projectName,
        skills: enabled,
        generatedAt: new Date().toISOString(),
      },
      null,
      2,
    )
    await fs.writeFile(skillsPath, skillsContent, { mode: 0o600 })

    // Also write a copy of the CLAUDE.md alongside skills.json so the persona-brief
    // builder can locate project context even on installs where the repo isn't
    // checked out locally.
    const claudeLocalPath = path.join(projectDir, 'CLAUDE.md')
    await fs.writeFile(claudeLocalPath, claudeMd, { mode: 0o600 })

    // 3. Emit event.
    const now = new Date()
    const payload: ProjectSDLCConfiguredPayload = {
      session_id: input.sessionId,
      project_id: input.projectId,
      claude_md_committed: committed,
      claude_md_sha: claudeMdSha,
      memory_entries_seeded: input.memoryEntryIds.length,
      skills_enabled: enabled,
      configured_at: now.toISOString(),
    }
    await this.eventStore.append({
      aggregate_id: input.projectId,
      aggregate_type: 'install',
      event_type: 'ProjectSDLCConfigured',
      payload: payload as unknown as Record<string, unknown>,
      actor: SYSTEM_ACTOR,
      trace_id: uuidv7(),
      occurred_at: now.toISOString(),
      schema_version: 1,
    })

    return {
      claudeMdCommitted: committed,
      claudeMdSha,
      skillsEnabled: enabled,
      skillsConfigPath: skillsPath,
    }
  }
}

export function createSystemTeacher(
  eventStore: EventStore,
  githubProvisioner: DefaultGithubProvisioner | null,
): SystemTeacher {
  return new DefaultSystemTeacher(eventStore, githubProvisioner)
}
