/**
 * vision/auto-decompose-subscriber.ts — EventStore subscriber that fires
 * VisionDecomposer.decompose() whenever a VisionLocked event lands.
 *
 * Registration:
 *   Call registerVisionAutoDecompose({ eventStore, db }) from boot.ts near
 *   registerVisionPMStub. Returns an unsubscribe function for graceful shutdown.
 *
 * Idempotency:
 *   Before calling decompose(), the subscriber checks whether a
 *   BacklogAutoDecomposed event already exists for this
 *   (vision_document_id, locked_version_number) pair. If yes, the event is
 *   silently skipped — re-locking the same version is a no-op.
 *
 *   Re-locking after a revise() produces a new locked_version_number, so a
 *   new decomposition runs producing a fresh set of epics + stories.
 *
 * Error handling:
 *   Errors during decompose() are logged but do not crash the process. The
 *   subscriber is fire-and-forget (void). The lock itself has already succeeded;
 *   backlog creation is a best-effort follow-up.
 */

import { eq, and } from 'drizzle-orm'
import { sql as dSQL } from 'drizzle-orm'
import type { EventStore } from '../events/store.js'
import type { DB } from '../db/client.js'
import { epics } from '../db/schema/backlog.js'
import { VisionDecomposer } from './auto-decompose.js'
import { logger } from '../config/logger.js'

// ---------------------------------------------------------------------------
// Deps interface
// ---------------------------------------------------------------------------

export interface AutoDecomposeDeps {
  eventStore: EventStore
  db: DB
}

// ---------------------------------------------------------------------------
// Idempotency check
// ---------------------------------------------------------------------------

/**
 * Returns true if auto-generated epics already exist in the DB for this
 * (vision_document_id, version_number) pair.
 *
 * We check the DB rows directly rather than the events log to avoid a race
 * condition where two concurrent invocations both see no BacklogAutoDecomposed
 * event before either has finished appending it. The DB rows are committed
 * inside the transaction before events are appended, so checking rows is a
 * stronger guard.
 *
 * The query uses a JSONB filter:
 *   auto_generated_metadata->>'vision_document_id' = $1
 *   AND (auto_generated_metadata->>'version')::int = $2
 */
async function wasAlreadyDecomposed(
  db: DB,
  visionDocumentId: string,
  versionNumber: number,
): Promise<boolean> {
  const rows = await db
    .select({ epicId: epics.epicId })
    .from(epics)
    .where(
      and(
        dSQL`${epics.autoGeneratedMetadata}->>'vision_document_id' = ${visionDocumentId}`,
        dSQL`(${epics.autoGeneratedMetadata}->>'version')::int = ${versionNumber}`,
      ),
    )
    .limit(1)

  return rows.length > 0
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

/**
 * Register the VisionAutoDecompose subscriber.
 *
 * Returns an unsubscribe function — call it in shutdown() LIFO order.
 *
 * Idempotency note:
 *   In addition to the DB-row check, we maintain a process-local in-flight
 *   set so that a burst of duplicate VisionLocked events (e.g. NOTIFY backfill
 *   on reconnect) doesn't race past the DB check before the first transaction
 *   commits. The in-flight key is released on completion (success or error).
 */
export function registerVisionAutoDecompose({ eventStore, db }: AutoDecomposeDeps): () => void {
  const decomposer = new VisionDecomposer(db, eventStore)

  // Keys: `${visionDocumentId}:${versionNumber}` — prevent concurrent double-runs.
  const inFlight = new Set<string>()

  const unsubscribe = eventStore.subscribe(null, (envelope) => {
    if (envelope.event_type !== 'VisionLocked') return

    const payload = envelope.payload as Record<string, unknown>
    const visionDocumentId =
      typeof payload['vision_document_id'] === 'string' ? payload['vision_document_id'] : null
    const versionNumber =
      typeof payload['version_number'] === 'number' ? payload['version_number'] : null

    if (!visionDocumentId || versionNumber === null) {
      logger.warn(
        { eventId: envelope.event_id, payload },
        'auto-decompose-subscriber: VisionLocked payload missing vision_document_id or version_number; skipping',
      )
      return
    }

    const key = `${visionDocumentId}:${versionNumber}`

    // Fast-path: another async handler for this key is already in-flight.
    if (inFlight.has(key)) {
      logger.debug(
        { visionDocumentId, versionNumber },
        'auto-decompose-subscriber: already in-flight for this key; skipping duplicate event',
      )
      return
    }
    inFlight.add(key)

    // Fire-and-forget: decompose asynchronously after idempotency check.
    void (async () => {
      try {
        const alreadyDone = await wasAlreadyDecomposed(db, visionDocumentId, versionNumber)
        if (alreadyDone) {
          logger.info(
            { visionDocumentId, versionNumber },
            'auto-decompose-subscriber: epics already exist for this version; skipping',
          )
          return
        }

        const result = await decomposer.decompose(visionDocumentId)

        logger.info(
          {
            visionDocumentId,
            versionNumber,
            epicCount: result.epic_count,
            storyCount: result.story_count,
          },
          'auto-decompose-subscriber: decomposition complete',
        )
      } catch (err) {
        logger.error(
          { err, visionDocumentId, versionNumber, eventId: envelope.event_id },
          'auto-decompose-subscriber: decompose() threw — lock already committed; backlog creation failed',
        )
      } finally {
        inFlight.delete(key)
      }
    })()
  })

  logger.info('auto-decompose-subscriber: registered')
  return unsubscribe
}
